apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bitnami-mariadb-backup-sidecar-env
stringData:
  CRON_TZ: America/New_York
  MARIADB_HOST: mariadb-headless
  MARIADB_DATABASE: test
  MARIADB_USER: root
  MARIADB_PASSWORD: root
  DAILY_BACKUP_DIR: /mnt/backup-daily
  MONTHLY_BACKUP_DIR: /mnt/backup-monthly
  RCLONE_S3_PROVIDER: Wasabi
  RCLONE_S3_ACCESS_KEY_ID: 
  RCLONE_S3_SECRET_ACCESS_KEY: 
  RCLONE_S3_REGION: us-east-2
  RCLONE_S3_ENDPOINT: s3.us-east-2.wasabisys.com
  RCLONE_S3_BUCKET_DAILY: immutable-backups-daily
  RCLONE_S3_BUCKET_MONTHLY: immutable-backups-daily